# Generated by Django 5.1.6 on 2025-02-25 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('grandfather_name', models.CharField(max_length=100)),
                ('emp_id', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='employee_images/')),
                ('region', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('woreda', models.CharField(max_length=100)),
                ('kebele', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('institution_name', models.CharField(max_length=200)),
                ('field', models.CharField(max_length=100)),
                ('date_of_graduate', models.DateField()),
                ('company_names', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('Receptionist', 'Receptionist'), ('Nurse', 'Nurse'), ('Doctor', 'Doctor')], default='Receptionist', max_length=20)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='employee_docs/')),
                ('licence_type', models.CharField(max_length=100)),
                ('give_date', models.DateField()),
                ('expired_date', models.DateField()),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_account', models.CharField(max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'permissions': [],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('grandfather_name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone_number', models.CharField(max_length=20)),
                ('card_no', models.CharField(max_length=50, unique=True)),
                ('kebele', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('woreda', models.CharField(max_length=100)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('symptoms', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'Doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_patients', to=settings.AUTH_USER_MODEL)),
                ('nurse', models.ForeignKey(limit_choices_to={'role': 'Nurse'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_patients', to=settings.AUTH_USER_MODEL)),
                ('receptionist', models.ForeignKey(limit_choices_to={'role': 'Receptionist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='PatientNurseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulse_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('oxygen_saturation', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nurse', models.ForeignKey(limit_choices_to={'role': 'Nurse'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_patient_details', to=settings.AUTH_USER_MODEL)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_details', to='clinic.patient')),
            ],
        ),
    ]
