# Generated by Django 5.1.6 on 2025-02-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review by Nurse'), ('IN_PROGRESS', 'In Progress by Nurse'), ('PENDING_DOCTOR', 'Pending Review by Doctor'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
