# Generated by Django 5.1.6 on 2025-02-28 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_patientdoctordetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='lab_technician',
            field=models.ForeignKey(limit_choices_to={'role': 'LabTechnician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='payment_status',
            field=models.BooleanField(default=False, help_text='Indicates if the lab payment has been made'),
        ),
        migrations.AddField(
            model_name='patientdoctordetail',
            name='lab_referral',
            field=models.BooleanField(default=False, help_text='Indicates if lab tests are required'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Receptionist', 'Receptionist'), ('Nurse', 'Nurse'), ('Doctor', 'Doctor'), ('LabTechnician', 'LabTechnician')], default='Receptionist', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review by Nurse'), ('IN_PROGRESS', 'In Progress by Nurse'), ('PENDING_DOCTOR', 'Pending Review by Doctor'), ('PENDING_LAB', 'Pending Laboratory Analysis'), ('PENDING_PAYMENT', 'Pending Payment for Lab'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='LaboratoryPatientDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(blank=True, max_length=100)),
                ('test_results', models.TextField(blank=True)),
                ('sample_collected', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_verified', models.BooleanField(default=False, help_text='Indicates if payment for lab tests has been verified')),
                ('lab_technician', models.ForeignKey(limit_choices_to={'role': 'LabTechnician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_patient_details', to=settings.AUTH_USER_MODEL)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_details', to='clinic.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('status', models.BooleanField(default=True, help_text='Indicates if the payment is confirmed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='clinic.patient')),
            ],
        ),
    ]
